[project]
name = "citycoin"

[contracts.sip-010-trait]
path = "contracts/clarinet/sip-10-ft-standard.clar"
depends_on = []

[contracts.citycoin]
path = "contracts/clarinet/citycoin.clar"
depends_on = ["sip-010-trait"]

[contracts.malicious]
path = "contracts/clarinet/malicious.clar"
depends_on = ["citycoin"]