[network]
name = "Development"

[accounts.deployer]
# ST1HTBVD3JG9C05J7HBJTHGR0GGW7KXW28M5JS8QE
mnemonic = "fetch outside black test wash cover just actual execute nice door want airport betray quantum stamp fish act pen trust portion fatigue scissors vague"
balance = 1_000_000

[accounts.wallet_1]
# ST1J4G6RR643BCG8G8SR6M2D9Z9KXT2NJDRK3FBTK
mnemonic = "spoil sock coyote include verify comic jacket gain beauty tank flush victory illness edge reveal shallow plug hobby usual juice harsh pact wreck eight"
balance = 1_000_000

[accounts.wallet_2]
# ST20ATRN26N9P05V2F1RHFRV24X8C8M3W54E427B2
mnemonic = "arrange scale orient half ugly kid bike twin magnet joke hurt fiber ethics super receive version wreck media fluid much abstract reward street alter"
balance = 1_000_000

[accounts.wallet_3]
# ST21HMSJATHZ888PD0S0SSTWP4J61TCRJYEVQ0STB
mnemonic = "glide clown kitchen picnic basket hidden asset beyond kid plug carbon talent drama wet pet rhythm hero nest purity baby bicycle ghost sponsor dragon"
balance = 1_000_000

[accounts.wallet_4]
# ST2QXSK64YQX3CQPC530K79XWQ98XFAM9W3XKEH3N
mnemonic = "pulp when detect fun unaware reduce promote tank success lecture cool cheese object amazing hunt plug wing month hello tunnel detect connect floor brush"
balance = 1_000_000

[accounts.wallet_5]
# ST3DG3R65C9TTEEW5BC5XTSY0M1JM7NBE7GVWKTVJ
mnemonic = "replace swing shove congress smoke banana tired term blanket nominee leave club myself swing egg virus answer bulk useful start decrease family energy february"
balance = 1_000_000

[accounts.wallet_6]
# ST3R3B1WVY7RK5D3SV5YTH01XSX1S4NN5B3QK2X0W
mnemonic = "apology together shy taxi glare struggle hip camp engage lion possible during squeeze hen exotic marriage misery kiwi once quiz enough exhibit immense tooth"
balance = 1_000_000

[accounts.wallet_7]
# ST3ZG8F9X4VKVTVQB2APF4NEYEE1HQHC2EDBF09JN
mnemonic = "antenna bitter find rely gadget father exact excuse cross easy elbow alcohol injury loud silk bird crime cabbage winter fit wide screen update october"
balance = 1_000_000

[accounts.wallet_8]
# STEB8ZW46YZJ40E3P7A287RBJFWPHYNQ2AB5ECT8
mnemonic = "east load echo merit ignore hip tag obvious truly adjust smart panther deer aisle north hotel process frown lock property catch bless notice topple"
balance = 1_000_000

[accounts.city_wallet]
# STFCVYY1RJDNJHST7RRTPACYHVJQDJ7R1DWTQHQA
mnemonic = "market ocean tortoise venue vivid coach machine category conduct enable insect jump fog file test core book chaos crucial burst version curious prosper fever"
balance = 0