# GitHub action to run Clarinet tests against the contracts
# and fail if code is invalid or a test fails.

# Uses a prepare script outlined in testing section of README

name: Contract Tests

# Controls when the action will run.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Prepare contract files"
        run: ./scripts/clarinet-prepare.sh
      - name: "Check contract syntax"
        uses: docker://hirosystems/clarinet:latest
        with:
          args: check
      - name: "Execute test suite"
        uses: docker://hirosystems/clarinet:latest
        with:
          args: test ./tests/citycoin-core.test.ts
      #- name: "Upload code coverage"
      #  uses: codecov/codecov-action@v2
      #  with:
      #    files: ./coverage.lcov
